/**
 * Data-driven combat skill registry.
 */

export const DEFAULT_SKILLS = {
  light_punch: {
    id: 'light_punch',
    name: 'Neon Jab',
    kind: 'normal',
    startupFrames: 4,
    activeFrames: 3,
    recoveryFrames: 8,
    damage: 4,
    guardDamage: 1,
    hitbox: { x: 18, y: -42, width: 32, height: 26 },
    knockback: { x: 10, y: 0 },
    hitSpark: 'small',
    rageCost: 0,
    cooldownFrames: 10,
    hitstunFrames: 14,
    blockstunFrames: 7,
    tags: ['poke', 'confirm_starter'],
  },
  heavy_strike: {
    id: 'heavy_strike',
    name: 'Steam Hammer',
    kind: 'normal',
    startupFrames: 9,
    activeFrames: 4,
    recoveryFrames: 18,
    damage: 8,
    guardDamage: 3,
    hitbox: { x: 22, y: -46, width: 46, height: 34 },
    knockback: { x: 20, y: 0 },
    hitSpark: 'large',
    rageCost: 0,
    cooldownFrames: 24,
    hitstunFrames: 18,
    blockstunFrames: 11,
    tags: ['punish', 'high_commitment'],
  },
  medium_kick: {
    id: 'medium_kick',
    name: 'Neon Roundhouse',
    kind: 'normal',
    startupFrames: 6,
    activeFrames: 3,
    recoveryFrames: 12,
    damage: 6,
    guardDamage: 2,
    hitbox: { x: 20, y: -48, width: 42, height: 30 },
    knockback: { x: 14, y: 0 },
    hitSpark: 'small',
    rageCost: 0,
    cooldownFrames: 16,
    hitstunFrames: 14,
    blockstunFrames: 9,
    tags: ['poke', 'spacing'],
  },
  throw: {
    id: 'throw',
    name: 'Cyber Grapple',
    kind: 'throw',
    startupFrames: 5,
    activeFrames: 2,
    recoveryFrames: 16,
    damage: 7,
    guardDamage: 0,
    hitbox: { x: 8, y: -40, width: 28, height: 36 },
    knockback: { x: 18, y: 0 },
    hitSpark: 'large',
    rageCost: 0,
    cooldownFrames: 30,
    hitstunFrames: 16,
    blockstunFrames: 0,
    canBeBlocked: false,
    tags: ['throw', 'mixup'],
  },
  guard: {
    id: 'guard',
    name: 'Chrome Guard',
    kind: 'defense',
    startupFrames: 1,
    activeFrames: 12,
    recoveryFrames: 4,
    damage: 0,
    guardDamage: 0,
    rageCost: 0,
    cooldownFrames: 8,
    tags: ['defense'],
  },
  neon_overdrive: {
    id: 'neon_overdrive',
    name: 'Neon Overdrive',
    kind: 'ultimate',
    startupFrames: 12,
    activeFrames: 6,
    recoveryFrames: 30,
    damage: 30,
    minDamage: 16,
    guardDamage: 8,
    hitbox: { x: 16, y: -58, width: 92, height: 54 },
    knockback: { x: 28, y: 0 },
    hitSpark: 'cinematic',
    rageCost: 100,
    cooldownFrames: 90,
    canBeBlocked: true,
    canBeInterrupted: true,
    cinematic: true,
    tags: ['cinematic_super', 'kill_confirm'],
  },
  steam_reversal: {
    id: 'steam_reversal',
    name: 'Steam Reversal',
    kind: 'ultimate',
    startupFrames: 5,
    activeFrames: 5,
    recoveryFrames: 36,
    damage: 24,
    minDamage: 12,
    guardDamage: 5,
    hitbox: { x: 10, y: -54, width: 72, height: 50 },
    knockback: { x: 24, y: 0 },
    hitSpark: 'large',
    rageCost: 100,
    cooldownFrames: 100,
    invulnFrames: 4,
    canBeBlocked: true,
    canBeInterrupted: false,
    cinematic: false,
    tags: ['reversal_super', 'comeback'],
  },
  dash: {
    id: 'dash',
    name: 'Neon Dash',
    kind: 'motion',
    startupFrames: 1,
    activeFrames: 4,
    recoveryFrames: 2,
    damage: 0,
    guardDamage: 0,
    rageCost: 0,
    cooldownFrames: 10,
    motionPath: 'forward_dash',
    tags: ['mobility', 'approach'],
  },
  back_dash: {
    id: 'back_dash',
    name: 'Back Dash',
    kind: 'motion',
    startupFrames: 1,
    activeFrames: 4,
    recoveryFrames: 2,
    damage: 0,
    guardDamage: 0,
    rageCost: 0,
    cooldownFrames: 12,
    motionPath: 'back_step',
    invulnFrames: 2,
    tags: ['mobility', 'retreat'],
  },
  neon_orb: {
    id: 'neon_orb',
    name: 'Neon Orb',
    kind: 'projectile',
    startupFrames: 6,
    activeFrames: 1,
    recoveryFrames: 10,
    damage: 5,
    guardDamage: 2,
    hitbox: { x: 20, y: -50, width: 16, height: 16 },
    knockback: { x: 12, y: 0 },
    hitSpark: 'large',
    rageCost: 30,
    cooldownFrames: 28,
    projectile: {
      speed: 12,
      lifetimeFrames: 40,
      width: 16,
      height: 16,
      yOffset: -44,
    },
    hitstunFrames: 12,
    blockstunFrames: 8,
    tags: ['zoning', 'projectile'],
  },
  parry: {
    id: 'parry',
    name: 'Perfect Parry',
    kind: 'defense',
    startupFrames: 1,
    activeFrames: 3,
    recoveryFrames: 6,
    damage: 0,
    guardDamage: 0,
    rageCost: 0,
    cooldownFrames: 18,
    parryWindowFrames: 3,
    tags: ['defense', 'counter'],
  },
  crouch_kick: {
    id: 'crouch_kick',
    name: 'Low Sweep',
    kind: 'normal',
    startupFrames: 5,
    activeFrames: 3,
    recoveryFrames: 14,
    damage: 5,
    guardDamage: 2,
    hitbox: { x: 16, y: -20, width: 40, height: 20 },
    knockback: { x: 8, y: 0 },
    hitSpark: 'small',
    rageCost: 0,
    cooldownFrames: 14,
    hitstunFrames: 16,
    blockstunFrames: 8,
    posture: 'crouch',
    tags: ['low', 'poke', 'crouch'],
  },
  jump_kick: {
    id: 'jump_kick',
    name: 'Aerial Kick',
    kind: 'normal',
    startupFrames: 4,
    activeFrames: 4,
    recoveryFrames: 12,
    damage: 6,
    guardDamage: 2,
    hitbox: { x: 14, y: -60, width: 36, height: 30 },
    knockback: { x: 12, y: 4 },
    hitSpark: 'small',
    rageCost: 0,
    cooldownFrames: 18,
    hitstunFrames: 14,
    blockstunFrames: 9,
    posture: 'jump',
    tags: ['overhead', 'jump', 'mixup'],
  },
};

export class SkillRegistry {
  constructor(skills = DEFAULT_SKILLS) {
    this._skills = new Map(Object.entries(skills));
  }

  get(skillId) {
    return this._skills.get(skillId) || null;
  }

  list() {
    return [...this._skills.values()];
  }

  getDefaultAttack() {
    return this.get('light_punch');
  }

  getDefaultUltimate(policy = 'confirm_only') {
    if (policy === 'reversal_when_low') {
      return this.get('steam_reversal');
    }
    return this.get('neon_overdrive');
  }
}
